name: "Servoy WAR Builder"
author: "Servoy Components"
description: "A GitHub Action used to build Servoy WAR files."
inputs:
  servoy-version:
    description: "The full Servoy version to use for the build (ex. '2023.03.2.3844')"
    required: true
  api-key:
    description: "API key obtained from the ServoyComponents website from either the commercial license (https://servoycomponents.com/components/plugins) or the All Products Pack (https://servoycomponents.com/all-products-pack)"
    required: true
  solution-name:
    description: "Name of the primary solution to export to the WAR file"
    required: true
  default-admin-user:
    description: "Default admin username to include in the WAR file"
    required: true
  default-admin-password:
    description: "Default admin password to include in the WAR file"
    required: true
  properties-file:
    description: "Path and name of the properties file used to start the exporter"
  ignore-build-errors:
    description: "Ignores build errors (warning: use of this flag is discouraged; it can cause invalid solutions to be exported)"
  skip-build:
    description: "No build markers will be generated. This can greatly decrease export time (warning: use of this flag is discouraged; it can cause invalid solutions to be exported)"
  dbi:
    description: "Export based on DBI files (even if database servers are available)"
  properties-file-war:
    description: "Path and name of the properties file to be included in the WAR"
  beans:
    description: "Space separated list of (smart/web client) beans to export (default: all beans are exported)"
  exclude-beans:
    description: "Space separated list of beans to be excluded from the export"
  lafs:
    description: "Space separated list of look-and-feels (smart client) to export (default: all lafs are exported)"
  exclude-lafs:
    description: "Space separated list of look-and-feels to be excluded from the export"
  drivers:
    description: "Space separated list of JDBC (database) drivers to export (default: all drivers are exported)"
  exclude-drivers:
    description: "Space separated list of drivers to be excluded from the export"
  plugins:
    description: "Space separated list of plugins to export (default: all plugins are exported)"
  exclude-plugins:
    description: "Space separated list of plugins to be excluded from the export"
  additional-solutions:
    description: "Space separated list of solutions that must be exported, but are not in the current solution's modules (for example, solutions for batch processors)"
  components:
    description: "Space separated list of components to export (default: all components are exported)"
    default: "all"
  exclude-components:
    description: "Space separated list of components to be excluded from the export"
  services:
    description: "Space separated list of services to export (default: all services are exported)"
    default: "all"
  exclude-services:
    description: "Space separated list of services to be excluded from the export"
  export-metadata:
    description: "Export metadata tables"
  check-metadata:
    description: "Check that metadata for metadata tables is the same for each table, both in the according workspace file and in the actual table in the database before exporting"
  sample-data:
    description: "Export sample data"
  sample-data-row-count:
    description: "Number of rows of sample data to export per table"
  i18n:
    description: "Export i18n data"
  users:
    description: "Exports users"
  tables:
    description: "Export all table information about tables from referenced servers"
  war-file-name:
    description: "The name of the WAR file"
  overwrite-groups:
    description: "Overwrites groups"
  allow-sql-keywords:
    description: "Allows SQL keywords"
  stop-on-data-model-changes:
    description: "Stops import if the data model changes"
  allow-data-model-changes:
    description: "A space separated list of server names that allow data model changes. If the list is missing, then data model changes are allowed on all servers"
  skip-database-views-update:
    description: "Skips database views update"
  override-sequence-types:
    description: "Overrides sequence types"
  override-default-values:
    description: "Overrides default values"
  insert-new-i18n-keys-only:
    description: "Inserts new i18n keys only"
  import-user-policy:
    description: "0 = don't, 1 = create users & update groups, 2 = overwrite completely"
  add-users-to-admin-group:
    description: "Adds users to admin group"
  update-sequences:
    description: "Updates sequences"
  upgrade-repository:
    description: "Automatically upgrade repository if needed"
  context-file-name:
    description: "Path to a Tomcat context.xml that should be included into the WAR/META-INF/context.xml"
  use-as-real-admin-user:
    description: "The default user login will be available as a normal admin user in the solutions as well"
  do-not-overwrite-db-server-properties:
    description: "SKIP overwrite of old DB server properties"
  overwrite-all-properties:
    description: "Overwrite all (potentially changed via admin page) properties of a previously deployed WAR application with the values from the servoy.properties of this WAR export"
  log4j-configuration-file:
    description: "A path to a Log4J configuration file that should be included instead of the default one"
  web-xml-file-name:
    description: "A path to a web.xml that should be included instead of the default one"
  ng2:
    description: "Export Titanium NG2 binaries. If 'sourcemaps' is given, sourcemaps will be generated for .ts files - useful for debugging"
  ng1:
    description: "Export NG1 client resources"
runs:
  using: 'node16'
  pre: 'setup.js'
  main: 'index.js'
  post: 'cleanup.js'
